# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProvideAged' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProvideAged

pod 'MJRefresh', '~> 3.7.2'
pod 'Masonry', '~> 1.1.0'
pod 'BRPickerView', '~> 2.8.0'
pod 'SVProgressHUD', '~> 2.2.5'
pod 'AFNetworking', '~> 4.0.1'
pod 'SDWebImage', '~> 5.11.1'
pod 'IQKeyboardManager', '~> 6.5.6'
pod 'MJExtension', '~> 3.3.0'
pod 'JPush', '~> 4.3.0'
pod 'Charts', '~> 4.1.0'

end
